### ISSUE TITLE
License ?

### ISSUE THREAD

**Issue by suprafun** [jykgod/QuadTreeAStarPathFindingForUnity#1]
Hello, under what license is this project released under ? I would like to study it to learn from it. Thank you.

**Comment by jykgod** [comment]
No license. You are free to use it in any way~

**Comment by suprafun** [comment]
Thank you so very much. Would it be possible for you to please upload a formal license to the repo. ( e.g. MIT, GPL, BSD, whatever you prefer). I ask so I can be sure of how I should treat this project. Thank you.
